### PR TITLE
Support openssl 1.3

### PR DESCRIPTION
**Pull request by skoppe**
On latest ArchLinux it didn't run anymore...

### CODE REVIEW

**Comment by ikod** [comment]
Thanks!

**Comment by WebFreak001** [comment]
I think this added support for openssl 3.1, no?

**Comment by skoppe** [comment]
> I think this added support for openssl 3.1, no?

The version I got was 1.3 though... That or this library mixed up the major/minor in here https://github.com/ikod/dlang-requests/blob/8ecd4bcd95c16c5ecdbe62a701416487702a7dfa/source/requests/ssl_adapter.d#L258

**Comment by ikod** [comment]
Sorry, I didn't tested this PR. Will try now.

**Comment by ikod** [comment]
Can you please check latest commit?

**Comment by WebFreak001** [comment]
at least the change added in this PR is important for things to start working on Ubuntu 22.04 with libssl-dev installed, where otherwise it would break without this PR applied (the `1,3` version)

**Comment by ikod** [comment]
I pushed fixes, available tests passed. Please check

**Comment by WebFreak001** [comment]
Micah on discord has been testing this for me and confirms it's still fixed with master right now, at least in their test case with attempting to start serve-d.

**Comment by ikod** [comment]
Thanks! Will publish release.

**Pull request merged**
