### PR TITLE
Add dub.selections.json to .gitignore

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by PetarKirov** [comment]
Lock files should always be committed, even for libraries. Check out e.g. https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/ (this talks about yarn, but the same concepts apply to dub).

**Comment by nordlow** [comment]
Can someone make a tag?

**Comment by ikod** [comment]
done, thanks

**Comment by nordlow** [comment]
> @nordlow A lock file is a general concept implement by most language package managers. In the case of Dub, that's `dub.selections.json`. It is supposed to contain the complete set of dependency package names, versions, cryptographic hashes of the archives containing them and from where to obtain download them. Unfortunately, Dub doesn't include the hash of package archives, which makes building not fully reproducible: if someone force pushes a git tag of a package and dub-registry happens to goes down next time it starts it will fetch the new package tag, which can contain completely different contents (including malware).

Thanks a lot for that explanation. So what about adding support for such a seemingly very valuable feature, @s-ludwig.

**Comment by nordlow** [comment]
It is supposed to contain the complete set of dependency package names, versions, cryptographic hashes of the archives containing them and from where to obtain download them. Unfortunately, Dub doesn't include the hash of package archives.

What is meant by the word "archive" in this regard considering the code is transferred via Git? Pre-built binary archives?

**Comment by PetarKirov** [comment]
> > It is supposed to contain the complete set of dependency package names, versions, cryptographic hashes of the archives containing them and from where to obtain download them. Unfortunately, Dub doesn't include the hash of package archives.
> 
> What is meant by the word "archive" in this regard considering the code is transferred via Git?

There are several package suppliers. The default, which most people are familiar with, is [dub-registry](https://github.com/dlang/dub-registry) and it powers [code.dlang.org](https://code.dlang.org). dub-registry stores archives of all packages as zip files on its server. So, in most cases, `dub fetch` is simply a zip file download: https://github.com/dlang/dub/blob/v1.27.0/source/dub/packagesuppliers/registry.d#L51-L86

> Would it be possible to add support for that in dub?

Yes, but it would require changes to both dub-registry and dub.

**Comment by nordlow** [comment]
> Yes, but it would require changes to both dub-registry and dub.

Seems to me like something worth investing in, @John-Colvin @skoppe.

**Pull request merged**
