### PR TITLE
Add support for latest libssl 3.0.x as new on Ubuntu 22.04

### PR DESCRIPTION
**Pull request by cschlote**
Add version 0.3 to test matrix. Tests for dmd and ldc2 seem to complete.

### CODE REVIEW

**Comment by ikod** [comment]
Hello, @cschlote 

Thans for PR!
I have to test changes. This will take some time.

**Comment by ikod** [comment]
Hello, @cschlote 

For me clean ubuntu 22.04 require also this patch
```
diff --git a/source/requests/ssl_adapter.d b/source/requests/ssl_adapter.d
index d4fb0a1..206a726 100755
--- a/source/requests/ssl_adapter.d
+++ b/source/requests/ssl_adapter.d
@@ -82,6 +82,7 @@ shared static this() {
             "libssl.so.1.0.2",
             "libssl.so.1.0.1",
             "libssl.so.1.0.0",
+            "libssl.so.3",
             "libssl.so",
         ];
         immutable string[] libcryptoname = [
@@ -89,6 +90,7 @@ shared static this() {
             "libcrypto.so.1.0.2",
             "libcrypto.so.1.0.1",
             "libcrypto.so.1.0.0",
+            "libcrypto.so.3",
             "libcrypto.so",
         ];
     } else
```

what do you think&

**Comment by cschlote** [comment]
Ah, ok, I forgot this. I have now clean Ubuntu, but some upgrade. Maybe there were some remains from the previous release. I checked my lokal system again. 

I guess, if you try to open libraries, the new and latest one should be first in the table, isn't it? Otherwise you might open some older library, if it is still installed.

I updated and tested my PR again.

**Comment by ikod** [comment]
Thanks!

**Comment by cschlote** [comment]
Don'T forget to tag the next release, so downstream project like serve-d or similiar can be recompiled with it ;_)

**Pull request merged**
