### PR TITLE
Add Meson build definition, update Debian packaging

### PR DESCRIPTION
**Pull request by ximion**
Hi!
I had this change floating around, and I thought you may find it useful.
Adding a Meson build definition will allow projects not using dub (e.g. also Meson projects or projects using Autotools or plain Makefiles) to use this D library, and also make Debian packaging possible.

Since you had some Debian packaging already, I adjusted the packaging a bit to be very close to something we would actually ship in Debian.
That includes creating a runtime and a development library package, updating to a recent debhelper compat level, using dh-dlang to set the right DFLAGS and automatically detecting library dependencies.

If you want to, I can split off the Debian stuff into a separate PR. Also, the tests don't seem to work in Meson, apparently some webserver isn't started (?), that needs a bit of further investigation.

Also, shipping the `debian/` directory in the root directory of upstream's code is still discouraged by Debian (although not being a complete dealbreaker, like in the past). Usually, people throw it in a subdirectory and then move it to the top level for building Debian packages upstream.

There is, however, and even better solution: Maintaining the package in Debian ;-) If you are interested in that, please get in touch - in that case, you could maintain the package directly in Debian and be part of the [Debian D Team](https://salsa.debian.org/d-team/).

Cheers,
    Matthias

### CODE REVIEW

**Comment by ikod** [comment]
Hello,
Thanks for this PR! Will check and merge very soon.
Probably I'll have some questions later.

чт, 17 Май 2018 г., 16:59 Matthias Klumpp <notifications@github.com>:

**Comment by ikod** [comment]
Hello @ximion 

how I can I support package in Debian repo?

**Comment by ximion** [comment]
@ikod I've already sent you a reply to your mail, but just for the record in case anyone else is interested:

How familiar are you with Debian packaging? There are guidelines for
new package maintainers[1], but they are quite excessive.
What you need to know though is:

 1) How to build a package with pbuilder or sbuild
 2) How to maintain packages in Git with git-buildpackage (gbp), some
info can be found at [2]
 3) How to use lintian[3]

In the Debian D Team, all packages are maintained together, so any
member of the team can make changes to any package in Git. If you are
no Debian Developer or Debian Maintainer, you can not make uploads to
Debian directly, but another team member can, in this case I will make
package uploads on your behalf (sponsored uploads), but you will
receive all the bug reports and QA information and have your name
listed as uploader of the package (the maintainer is always the D
team).

To get a repository for your new package at Debian that you can commit
to, you'll need an account at Salsa. Check out the salsa documentation
at [4] or go directly to https://signup.salsa.debian.org/ and create a
guest account.
I can then add you to the team at https://salsa.debian.org/d-team/

Packages in the D Team are - at the moment - maintained using the
import-orig-tar method, so for each upstream release we run gbp
import-orig <tarball> on the published tarballs. You can also use
other methods though, if you want to.
For an example on how packaging looks like, I recommend the
mustache-d[5] package.

In any case, don't worry about doing things wrong or too much
information, I can help you with any questions and the packaging
itself and guide you through the process.

**Comment by ikod** [comment]
Thanks, @ximion !

Merged. Something should be done to automatically adapt current version in changelog (it builds 0.0.7 instead of 0.8.x)

**Comment by ikod** [comment]
Hello, @ximion 

Can you please help with this - recently I added cachetools as dependency for dlang-requests and it breaks meson build. How I can fix it?

Thanks

**Comment by ximion** [comment]
@ikod Cachetools will need a Meson build definition as well. I can maybe look into that next week. You could look at the D-YAML <--> Tinyendian relation or the Vibe.d <--> Dieg-NG relation to see how to set up a dependency like this.

**Comment by ikod** [comment]
hello, @ximion !

Thanks, will try

**Pull request merged**
